# Update all clerk dependencies except localizations and themes

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: '@clerk/*'
    ignore:
      - dependency-name: '@clerk/localizations'
      - dependency-name: '@clerk/themes'
    groups:
      clerk-dependencies:
        patterns:
          - '@clerk/*'
    versioning-strategy: increase
