name: Preview

on:
  issue_comment:
    types: [created]

jobs:
  snapshot:
    name: Build
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '!snapshot' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run snapshot command and capture output
        id: snapshot
        run: |
          output=$(pnpm dlx pkg-pr-new publish --compact)
          echo "command_output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: 'Snapshot command output:\n```\n' +
                    `${{ steps.snapshot.outputs.command_output }}` +
                    '\n```'
            })
