name: Snapshot

on: [push, pull_request]

jobs:
  snapshot:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create a snapshot version
        id: snapshot
        run: pnpm dlx pkg-pr-new publish './packages/vue-clerk' --compact --comment=off
